//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phonizer.Content {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("phonizer.Content.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///	max(p.post_date)																	as &apos;Date&apos;,
        ///	max(case when pm.meta_key = &apos;_billing_first_name&apos; then pm.meta_value end)			as &apos;Name&apos;,
        ///	coalesce(max(case when pm.meta_key = &apos;_billing_email&apos; then pm.meta_value end), &apos;&apos;)	as Email,
        ///	max(case when pm.meta_key = &apos;_billing_phone&apos; then pm.meta_value end)				as Phone,
        ///	max(case when pm.meta_key = &apos;_billing_address_1&apos; then pm.meta_value end) 			as Street,
        ///	max(case when pm.meta_key = &apos;_billing_address_2&apos; then pm.meta_value end) 			as HouseNumber,
        ///	(select
        ///		gro [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GetAllOrders {
            get {
                return ResourceManager.GetString("GetAllOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///	max(ID)	as Id
        ///	from wp_posts
        ///	where post_type = &apos;shop_order&apos;.
        /// </summary>
        internal static string GetMaxOrderId {
            get {
                return ResourceManager.GetString("GetMaxOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///	ID	as Id
        ///	from wp_posts
        ///	where post_type = &apos;shop_order&apos;
        ///		and ID &gt; @id
        ///	limit 1.
        /// </summary>
        internal static string GetNextOrderId {
            get {
                return ResourceManager.GetString("GetNextOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///	max(p.post_date)																	as &apos;Date&apos;,
        ///	max(case when pm.meta_key = &apos;_billing_first_name&apos; then pm.meta_value end)			as &apos;Name&apos;,
        ///	coalesce(max(case when pm.meta_key = &apos;_billing_email&apos; then pm.meta_value end), &apos;&apos;)	as Email,
        ///	max(case when pm.meta_key = &apos;_billing_phone&apos; then pm.meta_value end)				as Phone,
        ///	max(case when pm.meta_key = &apos;_billing_address_1&apos; then pm.meta_value end) 			as Street,
        ///	max(case when pm.meta_key = &apos;_billing_address_2&apos; then pm.meta_value end) 			as HouseNumber,
        ///	(select
        ///		gro [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GetOrderById {
            get {
                return ResourceManager.GetString("GetOrderById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///	[Id],
        ///	[Date],
        ///	[Name],  
        ///	[Phone],
        ///	[Email],
        ///	[Street],
        ///	[HouseNumber],
        ///	[OrderItems],
        ///	[OrderSum],
        ///	[PaymentMethod],
        ///	[Note]
        ///	from [dbo].[Order]
        ///	where [Phone] like &apos;%&apos; + @phonePattern + &apos;%&apos;.
        /// </summary>
        internal static string GetOrdersByPhoneLocal {
            get {
                return ResourceManager.GetString("GetOrdersByPhoneLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///	max(pmo.meta_id)															as Id,
        ///	max(p.post_date)															as &apos;Date&apos;,
        ///	max(case when pmo.meta_key = &apos;_billing_first_name&apos; then pmo.meta_value end)	as &apos;Name&apos;,
        ///	max(case when pmo.meta_key = &apos;_billing_phone&apos; then pmo.meta_value end)		as Phone,
        ///	max(case when pmo.meta_key = &apos;_billing_address_1&apos; then pmo.meta_value end)	as Street,
        ///	max(case when pmo.meta_key = &apos;_billing_address_2&apos; then pmo.meta_value end)	as HouseNumber,
        ///	(select
        ///		group_concat(order_item_name separator &apos; | &apos; )
        ///        from wp [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GetOrdersByPhoneWc {
            get {
                return ResourceManager.GetString("GetOrdersByPhoneWc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на insert into [dbo].[Order]
        ///(
        ///	[Id],
        ///	[Date],
        ///	[Name],
        ///	[Phone],
        ///	[Email],
        ///	[Street],
        ///	[HouseNumber],
        ///	[OrderItems],
        ///	[OrderSum],
        ///	[PaymentMethod],
        ///	[Note]
        ///)
        ///	values
        ///	(
        ///		@Id,
        ///		@Date,
        ///		@Name,
        ///		@Phone,
        ///		@Email,
        ///		@Street,
        ///		@HouseNumber,
        ///		@OrderItems,
        ///		@OrderSum,
        ///		@PaymentMethod,
        ///		@Note
        ///	).
        /// </summary>
        internal static string SaveOrdersInLocal {
            get {
                return ResourceManager.GetString("SaveOrdersInLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select 1 as bit;.
        /// </summary>
        internal static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
    }
}
